apps/inventory/config/routes.rb
Rails.application.routes.draw do
  # root "articles#index"
  resources :goods
end

apps/inventory/app/models/good.rb
# frozen_string_literal: true

# Good Model
class Good < ApplicationRecord
  belongs_to :owner, class_name: 'User'

  def self.categories
    %w[Vegetable Dairy Meat Beverage Ingredient].freeze
  end

  validates :category, inclusion: { in: categories }
end

apps/inventory/app/models/user.rb
class User < ApplicationRecord
  has_many :goods
end

apps/inventory/app/controllers/goods_controller.rb
# Goods Controller
class GoodsController < ApplicationController
  def index
    @goods = Good.all
  end

  def show
    @good = Good.find(params[:id])
  end

  def new
    @users = User.all
    @categories = Good.categories
    @good = Good.new
  end

  def create
    @good = Good.new(good_params)

    if @good.save
      redirect_to @good
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @good = Good.find(params[:id])
    if @good.destroy
      redirect_to goods_path, status: :see_other
    else
      render @good, status: :unprocessable_entity
    end
  end

  private

  def good_params
    params.required(:good).permit(:name, :category, :place, :quantity, :owner_id)
  end
end

apps/inventory/app/helpers/goods_helper.rb
module GoodsHelper
end

apps/inventory/app/views/goods/index.html.erb
<h1>Invetory Management App</h1>

<%# <h1 class="text-3xl font-bold underline">
    Hello world!
</h1> %>

<h3>Your Current Goods</h3>
<ul>
  <% @goods.each do |good| %>
    <li>
      <%= link_to good.name, good_path(good) %>
    </li>
  <% end %>
</ul>

<h3>Did you buy something? Let's <%= link_to "Register", new_good_path %>!</h3>

apps/inventory/app/views/goods/new.html.erb
<h1>Register a new stuff</h1>


<%= form_with model: @good, local: true, data: { turbo_frame: 'new_post_form' } do |form| %>
  <ul id="new_post_form">
    <li><%= form.text_field :name, placeholder: 'Name' %></li>
    <%# <li><%= form.text_area :content, placeholder: 'Content' %>
    <li><%= form.select :category, options_for_select(@categories), prompt: 'Select a category' %></li>
    <li><%= form.select :place, options_for_select([["Refregerator", "Refregerator"]]), prompt: 'Select a category' %></li>
    <li><%= form.select :quantity, options_for_select([[1, 1]]), prompt: 'Select a category' %></li>
    <li><%= form.collection_select :owner_id, @users, :id, :name, prompt: 'Select a user who own' %></li>
    <li><%= form.submit 'Register' %></li>
  </ul>
<% end %>

apps/inventory/app/views/goods/show.html.erb
<h1><%= @good.name %></h1>

<ul>
  <li>Category: <%= @good.category %></li>
  <li>Place: <%= @good.place %></li>
  <li>Quantity: <%= @good.quantity %></li>
</ul>

<div>
  <%= link_to "Delete", good_path(@good), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</div>

apps/inventory/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>